networks:
  microservice_user:


services:

  mysql:
    image: mariadb:10.5.8
    container_name: microservice_user_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - microservice_user

  phpmyadmin:
    container_name: microservice_user_phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8086:80'
    env_file:
      - .env
    networks:
      - microservice_user